### ISSUE TITLE
Optimization of hyperparameters on log scale

### ISSUE THREAD

**Issue by Devaraj-G** [alan-turing-institute/mogp_emulator#31]
Optimization of the hyperparameters in the log-scale:
https://stats.stackexchange.com/questions/299386/negative-values-of-hyperparameters-in-gaussian-process

so that the search is better, if the hyperparameters span different order of magnitudes:
https://stats.stackexchange.com/questions/259815/why-logarithmic-scale-for-hyper-parameter-optimization#259818

**Comment by edaub** [comment]
Hi Devaraj,

The code does use a logarithmic scale when optimizing the hyperparameters. Since parameters are constrained to be positive, we take the exponential of the values that you see prior to evaluating the covariance functions. This ensures that we have an unconstrained optimization problem, so the minimization algorithm does not need to worry about any bounds. As you note, this also ensures that if inputs are of wildly different scales, the optimization works better without having to scale the parameters yourself.

Let me know if any of this is unclear.

**Comment by Devaraj-G** [comment]
Many thanks Eric, for making this clear!
________________________________
